# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Qaro Trading"
description: > # this means to ignore newlines until "email:"
   A Moroccan trading company

email: yahya@qoratrading.com
#blog logo
logo: "/assets/images/greenQ2.png"
# df_logo.jpg"
# blog cover
cover: "/assets/images/morocco6.jpg"

name: 'Qaro Trading'
author: 'Qaro Trading'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://www.qarotrading.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/qarotrading
    desc: Follow us on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/yamahakawazaki
    desc: Connect with us on facebook
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	envelope
    url:	mailto:info@qarotrading.com
    desc:	Send an email
    share_url:
    share_title:
    share_link:

  #- icon:	phone
  #  url:	tel://+14054122673
  #  desc:	+1 (405) 412-2673
  #  share_url:
  #  share_title:
  #  share_link:
